# Generated by Django 5.1.15 on 2026-08-28 20:43

import core.midia
import core.validadores
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Informe apenas números.')])),
                ('razao_social', models.CharField(max_length=180)),
                ('nome_fantasia', models.CharField(db_index=True, max_length=120)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.midia.upload_logo_empresa, validators=[core.validadores.validar_imagem])),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('logradouro', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_cobranca', models.EmailField(blank=True, help_text='Remetente e caixa de resposta dos boletos enviados ao sacado.', max_length=254)),
                ('plano', models.CharField(choices=[('TESTE', 'Avaliação'), ('ESSENCIAL', 'Essencial'), ('PROFISSIONAL', 'Profissional'), ('ILIMITADO', 'Ilimitado')], db_index=True, default='TESTE', max_length=14)),
                ('cor_primaria', models.CharField(default='#1F4E79', max_length=7)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('suspensa_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_suspensao', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tenants',
                'ordering': ('nome_fantasia',),
                'indexes': [models.Index(fields=['ativa', 'nome_fantasia'], name='tenants_ativa_2288fe_idx')],
            },
        ),
    ]
