# Generated by Django 5.1.15 on 2026-08-28 20:43

import core.midia
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, help_text='Sequencial por empresa. É o número que o operador diz no telefone.')),
                ('descricao', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=40)),
                ('seu_numero', models.CharField(blank=True, db_index=True, max_length=25)),
                ('nosso_numero', models.CharField(blank=True, db_index=True, max_length=20)),
                ('identificador_bancario', models.CharField(blank=True, db_index=True, max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_emissao', models.DateField(db_index=True)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('juros_mes_percentual', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('multa_percentual', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_limite_desconto', models.DateField(blank=True, null=True)),
                ('abatimento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('ENVIADA_AO_BANCO', 'Enviada ao banco'), ('REGISTRADA', 'Registrada'), ('DISPONIVEL', 'Disponível'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('BAIXADA', 'Baixada'), ('REJEITADA', 'Rejeitada'), ('ERRO', 'Erro')], db_index=True, default='RASCUNHO', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, db_index=True, null=True)),
                ('data_liquidacao', models.DateField(blank=True, db_index=True, help_text='Quando o dinheiro fica disponível. Difere da data de pagamento e é a que vale no fluxo de caixa.', null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_juros_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_multa_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto_concedido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('linha_digitavel', models.CharField(blank=True, max_length=60)),
                ('codigo_barras', models.CharField(blank=True, max_length=44)),
                ('url_boleto', models.URLField(blank=True, help_text='Boleto hospedado pelo banco, quando a API devolve um.')),
                ('boleto_pdf', models.FileField(blank=True, null=True, upload_to=core.midia.upload_boleto)),
                ('boleto_gerado_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_ao_cliente_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('mensagem_erro', models.CharField(blank=True, max_length=500)),
                ('chave_externa', models.CharField(blank=True, db_index=True, max_length=80)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='clientes.cliente')),
                ('conta_bancaria', models.ForeignKey(blank=True, help_text='Nulo só em rascunho: sem conta não há como registrar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='bancos.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='empresas.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='bancos.lotebancario')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'db_table': 'charges',
                'ordering': ('-data_vencimento', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='ItemCobranca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cobrancas.cobranca')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Item de cobrança',
                'verbose_name_plural': 'Itens de cobrança',
                'db_table': 'charge_items',
                'ordering': ('cobranca_id', 'ordem', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'status', 'data_vencimento'], name='charges_empresa_1aba37_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'cliente', '-data_vencimento'], name='charges_empresa_9644d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'conta_bancaria', 'status'], name='charges_empresa_577b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', '-data_pagamento'], name='charges_empresa_c817df_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'documento'], name='charges_empresa_723926_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['empresa', 'lote'], name='charges_empresa_034903_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(condition=models.Q(('status__in', ['PENDENTE', 'REGISTRADA', 'DISPONIVEL', 'ENVIADA_AO_BANCO'])), fields=['data_vencimento'], name='idx_cobranca_a_vencer'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_numero_cobranca_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('nosso_numero', ''), _negated=True), fields=('conta_bancaria', 'nosso_numero'), name='uniq_nosso_numero_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_externa', ''), _negated=True), fields=('empresa', 'chave_externa'), name='uniq_chave_externa_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(condition=models.Q(('data_vencimento__gte', models.F('data_emissao'))), name='vencimento_nao_antecede_emissao'),
        ),
        migrations.AddIndex(
            model_name='itemcobranca',
            index=models.Index(fields=['cobranca', 'ordem'], name='charge_item_cobranc_778b60_idx'),
        ),
    ]
