# Generated by Django 5.1.15 on 2026-08-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('cobrancas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciabancaria',
            name='cobranca',
            field=models.ForeignKey(blank=True, help_text='Nulo quando o título do retorno não existe aqui — acontece com título emitido direto no internet banking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='cobrancas.cobranca'),
        ),
        migrations.AddField(
            model_name='ocorrenciabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='contabancaria',
            index=models.Index(fields=['empresa', 'ativa'], name='contas_banc_empresa_f25c71_idx'),
        ),
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(fields=('empresa', 'banco', 'agencia', 'conta', 'carteira'), name='uniq_conta_carteira_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('empresa',), name='uniq_conta_padrao_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='arquivobancario',
            index=models.Index(fields=['empresa', 'tipo', '-recebido_em'], name='bank_files_empresa_a790da_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivobancario',
            index=models.Index(fields=['empresa', 'status'], name='bank_files_empresa_e0d0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivobancario',
            index=models.Index(fields=['status', 'tipo'], name='bank_files_status_afd234_idx'),
        ),
        migrations.AddConstraint(
            model_name='arquivobancario',
            constraint=models.UniqueConstraint(fields=('empresa', 'hash_arquivo'), name='uniq_hash_arquivo_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='lotebancario',
            index=models.Index(fields=['empresa', 'status', '-numero'], name='bank_batche_empresa_f7f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='lotebancario',
            index=models.Index(fields=['empresa', 'conta', '-criado_em'], name='bank_batche_empresa_e899cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotebancario',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_numero_lote_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciabancaria',
            index=models.Index(fields=['empresa', 'tipo', '-data_ocorrencia'], name='bank_occurr_empresa_b41835_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciabancaria',
            index=models.Index(fields=['empresa', 'nosso_numero'], name='bank_occurr_empresa_a4d4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciabancaria',
            index=models.Index(fields=['cobranca', '-data_ocorrencia'], name='bank_occurr_cobranc_def208_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciabancaria',
            index=models.Index(fields=['empresa', 'aplicada'], name='bank_occurr_empresa_3f53d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocorrenciabancaria',
            constraint=models.UniqueConstraint(fields=('arquivo', 'linha'), name='uniq_ocorrencia_por_linha'),
        ),
    ]
