# Generated by Django 5.1.15 on 2026-08-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(blank=True, max_length=160)),
                ('acao', models.CharField(db_index=True, max_length=24)),
                ('modulo', models.CharField(db_index=True, max_length=40)),
                ('objeto_tipo', models.CharField(blank=True, db_index=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('objeto_descricao', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('alteracoes', models.JSONField(blank=True, default=dict)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'db_table': 'auditoria_logs',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['empresa', '-criado_em'], name='auditoria_l_empresa_1d5253_idx'), models.Index(fields=['empresa', 'modulo', '-criado_em'], name='auditoria_l_empresa_0bf442_idx'), models.Index(fields=['usuario', '-criado_em'], name='auditoria_l_usuario_0eafd2_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='auditoria_l_objeto__349db6_idx')],
            },
        ),
    ]
