# Generated by Django 5.1.15 on 2026-08-28 20:43

import apps.accounts.models
import core.midia
import core.validadores
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nome_completo', models.CharField(max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.midia.upload_avatar_usuario, validators=[core.validadores.validar_imagem])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('plataforma_admin', models.BooleanField(db_index=True, default=False)),
                ('ultimo_acesso_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('empresa_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_padrao', to='empresas.empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ('nome_completo',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SegundoFator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('segredo', models.CharField(max_length=64)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('codigos_recuperacao', models.JSONField(blank=True, default=list)),
                ('ultimo_passo', models.BigIntegerField(blank=True, null=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_fator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segundo fator',
                'verbose_name_plural': 'Segundos fatores',
                'db_table': 'usuarios_segundo_fator',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FINANCEIRO', 'Financeiro'), ('OPERADOR', 'Operador'), ('CONSULTA', 'Consulta')], db_index=True, default='CONSULTA', max_length=16)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tenants',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='empresas',
            field=models.ManyToManyField(related_name='usuarios', through='accounts.UsuarioEmpresa', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='usuarioempresa',
            index=models.Index(fields=['empresa', 'ativo'], name='user_tenant_empresa_813957_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioempresa',
            index=models.Index(fields=['empresa', 'papel', 'ativo'], name='user_tenant_empresa_dad8d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuarioempresa',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa'), name='uniq_usuario_empresa'),
        ),
    ]
