# Generated by Django 5.1.15 on 2026-08-28 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.PositiveIntegerField(db_index=True, editable=False)),
                ('nome', models.CharField(db_index=True, help_text='Nome ou razão social, como consta no documento.', max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_secundario', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('logradouro', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=120)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('INADIMPLENTE', 'Inadimplente'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ATIVO', max_length=14)),
                ('codigo_externo', models.CharField(blank=True, db_index=True, max_length=60)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customers',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['empresa', 'status'], name='customers_empresa_13140e_idx'), models.Index(fields=['empresa', 'nome'], name='customers_empresa_2a39bc_idx'), models.Index(fields=['empresa', 'cidade', 'bairro'], name='customers_empresa_9446cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_codigo_cliente_por_empresa'), models.UniqueConstraint(condition=models.Q(('cpf_cnpj', ''), _negated=True), fields=('empresa', 'cpf_cnpj'), name='uniq_documento_cliente_por_empresa'), models.UniqueConstraint(condition=models.Q(('codigo_externo', ''), _negated=True), fields=('empresa', 'codigo_externo'), name='uniq_codigo_externo_cliente_por_empresa')],
            },
        ),
    ]
