# Generated by Django 5.1.15 on 2026-08-28 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('cobrancas', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('RETORNO', 'Retorno bancário'), ('API', 'Consulta à API do banco'), ('MANUAL', 'Baixa manual')], db_index=True, default='RETORNO', max_length=8)),
                ('data_pagamento', models.DateField(db_index=True, help_text='Quando o sacado pagou.')),
                ('data_credito', models.DateField(blank=True, db_index=True, help_text='Quando o dinheiro fica disponível na conta. É a data do fluxo de caixa, e costuma ser um ou dois dias depois.', null=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor pago pelo sacado, bruto.', max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('abatimento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('banco_recebedor', models.CharField(blank=True, max_length=3)),
                ('agencia_recebedora', models.CharField(blank=True, max_length=8)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('estornado', models.BooleanField(db_index=True, default=False, help_text='Pagamento desfeito pelo banco (devolução, cheque sem fundo). Nunca se apaga um pagamento — marca-se estornado, e o estorno também tem data e motivo.')),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.CharField(blank=True, max_length=300)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cobrancas.cobranca')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='bancos.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='empresas.empresa')),
                ('ocorrencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='bancos.ocorrenciabancaria')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Preenchido apenas em baixa manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'payments',
                'ordering': ('-data_pagamento', '-id'),
                'indexes': [models.Index(fields=['empresa', '-data_pagamento'], name='payments_empresa_9c0dd0_idx'), models.Index(fields=['empresa', '-data_credito'], name='payments_empresa_cfdd58_idx'), models.Index(fields=['empresa', 'cobranca'], name='payments_empresa_e4ffc3_idx'), models.Index(fields=['empresa', 'origem', '-data_pagamento'], name='payments_empresa_5d9fdc_idx'), models.Index(fields=['empresa', 'estornado', '-data_credito'], name='payments_empresa_410531_idx')],
            },
        ),
    ]
